# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controlsdialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ControlsDialog(object):
    def setupUi(self, ControlsDialog):
        ControlsDialog.setObjectName(_fromUtf8("ControlsDialog"))
        ControlsDialog.resize(929, 146)
        ControlsDialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.layoutWidget = QtGui.QWidget(ControlsDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 908, 138))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_9.addWidget(self.label_9)
        self.volume_slider = QtGui.QSlider(self.layoutWidget)
        self.volume_slider.setMinimumSize(QtCore.QSize(50, 0))
        self.volume_slider.setMaximumSize(QtCore.QSize(50, 16777215))
        self.volume_slider.setMaximum(100)
        self.volume_slider.setPageStep(1)
        self.volume_slider.setProperty("value", 100)
        self.volume_slider.setOrientation(QtCore.Qt.Horizontal)
        self.volume_slider.setObjectName(_fromUtf8("volume_slider"))
        self.horizontalLayout_9.addWidget(self.volume_slider)
        self.pushButton_10 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_10.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_10.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout_9.addWidget(self.pushButton_10)
        self.time_slider = QtGui.QSlider(self.layoutWidget)
        self.time_slider.setMaximum(10000)
        self.time_slider.setPageStep(1)
        self.time_slider.setOrientation(QtCore.Qt.Horizontal)
        self.time_slider.setTickPosition(QtGui.QSlider.NoTicks)
        self.time_slider.setObjectName(_fromUtf8("time_slider"))
        self.horizontalLayout_9.addWidget(self.time_slider)
        self.time_label = QtGui.QLabel(self.layoutWidget)
        self.time_label.setObjectName(_fromUtf8("time_label"))
        self.horizontalLayout_9.addWidget(self.time_label)
        self.fullscreen_button = QtGui.QPushButton(self.layoutWidget)
        self.fullscreen_button.setMinimumSize(QtCore.QSize(25, 25))
        self.fullscreen_button.setMaximumSize(QtCore.QSize(25, 25))
        self.fullscreen_button.setObjectName(_fromUtf8("fullscreen_button"))
        self.horizontalLayout_9.addWidget(self.fullscreen_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_7 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_7.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_5 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_5.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_6.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton = QtGui.QPushButton(self.layoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_2.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_3.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_4.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 3, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.speed_slider = QtGui.QSlider(self.layoutWidget)
        self.speed_slider.setMinimumSize(QtCore.QSize(75, 0))
        self.speed_slider.setMaximum(100)
        self.speed_slider.setPageStep(1)
        self.speed_slider.setProperty("value", 50)
        self.speed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.speed_slider.setInvertedAppearance(False)
        self.speed_slider.setObjectName(_fromUtf8("speed_slider"))
        self.horizontalLayout_3.addWidget(self.speed_slider)
        self.speed_label = QtGui.QLabel(self.layoutWidget)
        self.speed_label.setMinimumSize(QtCore.QSize(30, 0))
        self.speed_label.setMaximumSize(QtCore.QSize(30, 16777215))
        self.speed_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speed_label.setObjectName(_fromUtf8("speed_label"))
        self.horizontalLayout_3.addWidget(self.speed_label)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 1, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_10.addWidget(self.label_2)
        self.remote_box = QtGui.QComboBox(self.layoutWidget)
        self.remote_box.setObjectName(_fromUtf8("remote_box"))
        self.horizontalLayout_10.addWidget(self.remote_box)
        self.pushButton_11 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_11.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.horizontalLayout_10.addWidget(self.pushButton_11)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.filter_box = QtGui.QLineEdit(self.layoutWidget)
        self.filter_box.setMaximumSize(QtCore.QSize(100, 16777215))
        self.filter_box.setObjectName(_fromUtf8("filter_box"))
        self.horizontalLayout_7.addWidget(self.filter_box)
        self.pushButton_9 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_9.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout_7.addWidget(self.pushButton_9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        self.type_box = QtGui.QComboBox(self.layoutWidget)
        self.type_box.setMinimumSize(QtCore.QSize(100, 0))
        self.type_box.setObjectName(_fromUtf8("type_box"))
        self.horizontalLayout_8.addWidget(self.type_box)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.host_box = QtGui.QComboBox(self.layoutWidget)
        self.host_box.setMinimumSize(QtCore.QSize(300, 0))
        self.host_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.host_box.setObjectName(_fromUtf8("host_box"))
        self.horizontalLayout_4.addWidget(self.host_box)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.series_box = QtGui.QComboBox(self.layoutWidget)
        self.series_box.setMinimumSize(QtCore.QSize(300, 0))
        self.series_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.series_box.setObjectName(_fromUtf8("series_box"))
        self.horizontalLayout_5.addWidget(self.series_box)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.episode_box = QtGui.QComboBox(self.layoutWidget)
        self.episode_box.setMinimumSize(QtCore.QSize(300, 0))
        self.episode_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.episode_box.setObjectName(_fromUtf8("episode_box"))
        self.horizontalLayout_6.addWidget(self.episode_box)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.pushButton_8 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_8.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.verticalLayout_3.addWidget(self.pushButton_8)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 2, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 0, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_4)

        self.retranslateUi(ControlsDialog)
        QtCore.QObject.connect(self.pushButton_5, QtCore.SIGNAL(_fromUtf8("clicked()")), ControlsDialog.replay_button_clicked)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), ControlsDialog.next_episode_button_clicked)
        QtCore.QObject.connect(self.pushButton_7, QtCore.SIGNAL(_fromUtf8("clicked()")), ControlsDialog.prev_episode_button_clicked)
        QtCore.QObject.connect(self.pushButton_8, QtCore.SIGNAL(_fromUtf8("clicked()")), ControlsDialog.play_episode_clicked)
        QtCore.QObject.connect(self.pushButton_10, QtCore.SIGNAL(_fromUtf8("clicked()")), ControlsDialog.toggle_pause_clicked)
        QtCore.QObject.connect(self.host_box, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), ControlsDialog.host_box_changed)
        QtCore.QObject.connect(self.series_box, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), ControlsDialog.series_box_changed)
        QtCore.QObject.connect(self.episode_box, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), ControlsDialog.episode_box_changed)
        QtCore.QObject.connect(self.speed_slider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), ControlsDialog.speed_changed)
        QtCore.QObject.connect(self.volume_slider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), ControlsDialog.volume_changed)
        QtCore.QObject.connect(self.fullscreen_button, QtCore.SIGNAL(_fromUtf8("clicked()")), ControlsDialog.toggle_fullscreen)
        QtCore.QObject.connect(self.type_box, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), ControlsDialog.type_box_changed)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), ControlsDialog.large_jump_forwards_clicked)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), ControlsDialog.small_jump_forwards_clicked)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), ControlsDialog.small_jump_backwards_clicked)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), ControlsDialog.large_jump_backwards_clicked)
        QtCore.QObject.connect(self.filter_box, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), ControlsDialog.filter_changed)
        QtCore.QObject.connect(self.time_slider, QtCore.SIGNAL(_fromUtf8("sliderPressed()")), ControlsDialog.time_slider_pressed)
        QtCore.QObject.connect(self.time_slider, QtCore.SIGNAL(_fromUtf8("sliderReleased()")), ControlsDialog.time_slider_released)
        QtCore.QObject.connect(self.pushButton_9, QtCore.SIGNAL(_fromUtf8("clicked()")), self.filter_box.clear)
        QtCore.QObject.connect(self.time_slider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), ControlsDialog.time_slider_moved)
        QtCore.QObject.connect(self.pushButton_9, QtCore.SIGNAL(_fromUtf8("clicked()")), ControlsDialog.filter_changed)
        QtCore.QObject.connect(self.remote_box, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), ControlsDialog.remote_box_changed)
        QtCore.QObject.connect(self.pushButton_11, QtCore.SIGNAL(_fromUtf8("clicked()")), ControlsDialog.remote_refresh_clicked)
        QtCore.QMetaObject.connectSlotsByName(ControlsDialog)

    def retranslateUi(self, ControlsDialog):
        ControlsDialog.setWindowTitle(_translate("ControlsDialog", "PyWatch Controls", None))
        self.label_9.setText(_translate("ControlsDialog", "Volume", None))
        self.pushButton_10.setText(_translate("ControlsDialog", "▶", None))
        self.time_label.setText(_translate("ControlsDialog", "--:-- / --:--", None))
        self.fullscreen_button.setText(_translate("ControlsDialog", "[  ]", None))
        self.pushButton_7.setText(_translate("ControlsDialog", "<<", None))
        self.pushButton_5.setText(_translate("ControlsDialog", "↺", None))
        self.pushButton_6.setText(_translate("ControlsDialog", ">>", None))
        self.pushButton.setText(_translate("ControlsDialog", "-30", None))
        self.pushButton_2.setText(_translate("ControlsDialog", "-5", None))
        self.pushButton_3.setText(_translate("ControlsDialog", "+5", None))
        self.pushButton_4.setText(_translate("ControlsDialog", "+30", None))
        self.label.setText(_translate("ControlsDialog", "Speed", None))
        self.speed_label.setText(_translate("ControlsDialog", "100%", None))
        self.label_2.setText(_translate("ControlsDialog", "Remote", None))
        self.pushButton_11.setText(_translate("ControlsDialog", "↻", None))
        self.label_6.setText(_translate("ControlsDialog", "Filter", None))
        self.pushButton_9.setText(_translate("ControlsDialog", "X", None))
        self.label_7.setText(_translate("ControlsDialog", "Type", None))
        self.label_3.setText(_translate("ControlsDialog", "Host", None))
        self.label_4.setText(_translate("ControlsDialog", "Series", None))
        self.label_5.setText(_translate("ControlsDialog", "Episode", None))
        self.pushButton_8.setText(_translate("ControlsDialog", "▶", None))

